# Generated by Django 4.2.14 on 2024-08-03 14:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasksAPI', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permission', models.CharField(choices=[('read', 'Read'), ('update', 'Update')], max_length=20)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permission', to='tasksAPI.task')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permission', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('task', 'user', 'permission')},
            },
        ),
    ]
