# Generated by Django 4.2.14 on 2024-08-03 19:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasksAPI', '0002_taskpermission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskpermission',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to='tasksAPI.task'),
        ),
        migrations.AlterField(
            model_name='taskpermission',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to=settings.AUTH_USER_MODEL),
        ),
    ]
